# Generated by Django 5.2.7 on 2025-10-26 18:02

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('default_portion_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Размер порции')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='PortionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_short', models.CharField(max_length=10, verbose_name='Сокращение')),
            ],
            options={
                'verbose_name': 'Единица измерения порции',
                'verbose_name_plural': 'Единицы измерения порций',
            },
        ),
        migrations.CreateModel(
            name='IngredientPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Размер порции')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_plan_app.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Порция ингредиента',
                'verbose_name_plural': 'Порции ингредиентов',
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='portion_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_plan_app.portiontype', verbose_name='Единица измерения'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('instruction', models.TextField(verbose_name='Инструкция')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка')),
                ('ingredients', models.ManyToManyField(through='food_plan_app.IngredientPortion', through_fields=('recipe', 'ingredient'), to='food_plan_app.ingredient', verbose_name='Ингредиенты')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.AddField(
            model_name='ingredientportion',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_plan_app.recipe', verbose_name='Рецепт'),
        ),
        migrations.CreateModel(
            name='DailyRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_limit', models.IntegerField(default=5)),
                ('refresh_limit', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('refresh_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(db_default=datetime.datetime(2025, 10, 26, 18, 2, 43, 980293, tzinfo=datetime.timezone.utc))),
                ('disliked_recipes', models.ManyToManyField(blank=True, related_name='disliked', to='food_plan_app.recipe')),
                ('favorite_recipes', models.ManyToManyField(blank=True, related_name='favorited', to='food_plan_app.recipe')),
                ('history', models.ManyToManyField(blank=True, related_name='historical_daily_occurrences', to='food_plan_app.recipe')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_recipe', to='food_plan_app.recipe')),
            ],
            options={
                'verbose_name': 'Ежедневный рецепт',
                'verbose_name_plural': 'Ежедневные рецепты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='Телеграм id')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя')),
                ('daily_recipe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='food_plan_app.dailyrecipe', verbose_name='Предложенный рецепт')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ingredientportion',
            unique_together={('ingredient', 'recipe')},
        ),
    ]
