# Generated by Django 5.2.7 on 2025-10-26 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_plan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecipe',
            name='updated_at',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 10, 26, 18, 2, 50, 768483, tzinfo=datetime.timezone.utc)),
        ),
    ]
