# Generated by Django 5.2.7 on 2025-10-26 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_plan_app', '0004_alter_dailyrecipe_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='dailyrecipe',
            name='updated_at',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 10, 26, 18, 3, 24, 624576, tzinfo=datetime.timezone.utc)),
        ),
    ]
