# Generated by Django 5.2.7 on 2025-10-26 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_plan_app', '0005_recipe_is_available_alter_dailyrecipe_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecipe',
            name='updated_at',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 10, 26, 18, 4, 4, 341770, tzinfo=datetime.timezone.utc)),
        ),
    ]
